import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getLocation, locations, type Location } from "@/content/locations";
import {
  breadcrumbListSchema,
  faqPageSchema,
  graph,
  localBusinessSchema,
  type SchemaNode,
} from "@/lib/schema";
import { buildMetadata } from "@/lib/seo";
import { JsonLd } from "@/components/json-ld";
import { LocationCta } from "@/components/locations/location-cta";
import { LocationFaqs } from "@/components/locations/location-faq";
import { LocationHero } from "@/components/locations/location-hero";
import { LocationNarrative } from "@/components/locations/location-narrative";
import {
  LocationNearby,
  LocationPlaces,
} from "@/components/locations/location-coverage";
import { LocationServices } from "@/components/locations/location-services";

/**
 * =============================================================================
 * /locations/[city]/ — one page per served city
 * =============================================================================
 *
 * Twelve pages come out of this file, and the whole design problem is that they
 * must not read as one page twelve times. The differentiation lives in
 * content/locations.ts — every heading, every paragraph and every service
 * rationale is authored per city, and the city name is never interpolated into
 * prose. This file only assembles.
 *
 * `output: "export"` means there is no server: `generateStaticParams` below is
 * what makes these twelve routes exist at all, and `dynamicParams = false`
 * because a static export cannot render a param it did not build.
 */

/** Static export cannot serve params it did not prerender. */
export const dynamicParams = false;

export function generateStaticParams(): { city: string }[] {
  /*
   * Derived from the same `citySlug()` that content/site.ts uses to build the
   * route registry, so these twelve routes and the twelve sitemap entries are
   * the same twelve strings by construction rather than by coincidence.
   */
  return locations.map((location) => ({ city: location.slug }));
}

type CityPageProps = {
  /* Typed by hand rather than with the generated `PageProps<...>` helper: the
   * route types are only regenerated by `next build` / `next typegen`, and this
   * page has to typecheck before either has run. The shape is identical. */
  params: Promise<{ city: string }>;
};

export async function generateMetadata({
  params,
}: CityPageProps): Promise<Metadata> {
  const { city } = await params;
  const location = getLocation(city);

  if (!location) return {};

  /*
   * Title and description are authored per city in content/locations.ts and
   * length-checked by buildMetadata at build time. No template, because twelve
   * titles differing only by a city name is the duplicate-metadata pattern the
   * live-site audit already flagged elsewhere.
   */
  return buildMetadata({
    title: location.title,
    description: location.description,
    path: `/locations/${location.slug}/`,
  });
}

/**
 * `areaServed` for a single city page, nested city -> county -> state.
 *
 * More specific than the sitewide list of twelve, which is the point: this page
 * is about one market, and the county is the layer local search actually cares
 * about after the city name.
 */
function cityAreaServed(location: Location): SchemaNode {
  return {
    "@type": "City",
    name: location.city,
    containedInPlace: {
      "@type": "AdministrativeArea",
      name: location.county,
      containedInPlace: {
        "@type": "State",
        name: "Florida",
      },
    },
  };
}

export default async function CityPage({ params }: CityPageProps) {
  const { city } = await params;
  const location = getLocation(city);

  if (!location) notFound();

  const path = `/locations/${location.slug}/`;

  const crumbs = [
    { label: "Home", href: "/" },
    { label: "Locations", href: "/locations/" },
    { label: location.city },
  ];

  /*
   * The LocalBusiness node keeps the sitewide `@id` on purpose. This is one
   * business described from the angle of one market, not a second business with
   * a second address — so if the root layout also emits the entity, the two
   * merge on `@id` instead of competing. The `address` stays Casselberry on
   * every one of these pages, because that is where the business is.
   */
  const schema = graph(
    localBusinessSchema({
      areaServed: [cityAreaServed(location)],
    }),
    breadcrumbListSchema(
      crumbs.map((crumb) => ({ name: crumb.label, path: crumb.href })),
      { path },
    ),
    faqPageSchema(location.faqs, { path }),
  );

  /*
   * Closing CTA copy is the one block on the page that varies by tier rather
   * than by city. That is a deliberate line: section furniture repeating is
   * normal, whereas the market analysis, the service rationale and the FAQs
   * repeating is what makes a set of location pages a doorway set.
   */
  const cta = ctaCopy(location);

  return (
    <>
      <JsonLd id={`schema-location-${location.slug}`} data={schema} />

      <LocationHero location={location} crumbs={crumbs} />

      <LocationNarrative
        eyebrow="The market"
        heading={location.marketHeading}
        paragraphs={location.market}
        aside={
          <>
            <LocationPlaces location={location} />
            <LocationNearby location={location} />
          </>
        }
      />

      <LocationServices
        location={location}
        heading={location.servicesHeading}
      />

      <LocationNarrative
        eyebrow="How it works"
        heading={location.approachHeading}
        paragraphs={location.approach}
        divided
      />

      <LocationFaqs city={location.city} faqs={location.faqs} />

      <LocationCta heading={cta.heading} body={cta.body} />
    </>
  );
}

function ctaCopy(location: Location): { heading: string; body: string } {
  if (location.tier === "studio") {
    return {
      heading: "The studio is on Concord Drive. Come and see it.",
      body: "Book a strategy call and we will look at what you are running now, what it is costing you, and what a quarter of ad creative filmed here would actually change.",
    };
  }

  if (location.tier === "metro") {
    return {
      heading: `Filming in ${location.city} is a short drive, not a project`,
      body: "Book a strategy call. We will go through your current campaigns and what a production day in your own space would produce, before anyone quotes anything.",
    };
  }

  return {
    heading: `Working with ${location.city} from a Casselberry studio`,
    body: "Book a strategy call and we will be straight about which parts of this run remotely, what a production trip involves, and whether that is the right fit for you.",
  };
}
